[package]
name = "microsystem-init"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
microsystem-abi = { path = "../../crates/abi" }
microsystem-identity = { path = "../../crates/identity" }
microsystem-block = { path = "../block" }
microsystem-shell = { path = "../shell" }
microsystem-kernel = { path = "../../crates/kernel" }
sha2 = { version = "0.10", default-features = false, features = ["force-soft"] }
microsystem-user-rt = { path = "../../crates/user-rt", optional = true }

[features]
default = []
user-bin = ["dep:microsystem-user-rt"]

[[bin]]
name = "microsystem-init"
path = "src/main.rs"
test = false
bench = false
required-features = ["user-bin"]
